# config.yaml
models:
  default: mimo   # 默认使用的模型 id

  # grok:
  #   provider: openrouter
  #   model_name: x-ai/grok-4.1-fast:free
  #   base_url_env: https://openrouter.ai/api/v1
  #   stream: false

  mimo_openrouter:
    provider: openrouter
    model_name: xiaomi/mimo-v2-flash:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  mimo:
    provider: xiaomi
    model_name: mimo-v2-flash
    base_url_env: https://api.xiaomimimo.com/v1
    stream: false
  devstral:
    provider: openrouter
    model_name: mistralai/devstral-2512:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  deepseek-v3.1-nex-n1:
    provider: openrouter
    model_name: nex-agi/deepseek-v3.1-nex-n1:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  qwen3-max:
    provider: openrouter
    model_name: qwen/qwen3-max
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  qwen3-235b-a22b:
    provider: openrouter
    model_name: qwen/qwen3-235b-a22b-thinking-2507
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  qwen3-4b:
    provider: openrouter
    model_name: qwen/qwen3-4b:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  qwen3-32b:
    provider: openrouter
    model_name: qwen/qwen3-32b
    base_url_env: https://openrouter.ai/api/v1
    stream: true

  ds-v3.2:
    provider: openrouter
    model_name: deepseek/deepseek-v3.2
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  qwen-turbo:
    provider: openrouter
    model_name: qwen/qwen-turbo
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  grok:
    provider: openrouter
    model_name: x-ai/grok-4.1-fast
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  grok4:
    provider: openrouter
    model_name: x-ai/grok-4-fast
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  deepseekv3.2:
    provider: modelscope
    model_name: deepseek-ai/DeepSeek-V3.2
    base_url_env: https://api-inference.modelscope.cn/v1
    stream: false

  deepseekv3.1:
    provider: modelscope
    model_name: deepseek-ai/DeepSeek-V3.1
    base_url_env: https://api-inference.modelscope.cn/v1
    stream: false

  qwen3max_dashscope:
    provider: dashscope
    model_name: qwen3-max
    stream: false

  qwenplus_dashscope:
    provider: dashscope
    model_name: qwen-plus
    stream: false

  qwenflash_dashscope:
    provider: dashscope
    model_name: qwen-flash
    stream: false

  doubao_ark:
    provider: ark
    model_name: ep-20250904234628-hj9k8
    base_url_env: https://ark-ap-southeast.byteintl.net/api/v3
    stream: false

pdf_style:
  base_color: "#1F4E79"
  body_font_path: "C:/Windows/Fonts/msyh.ttc"
  heading_font_path: "C:/Windows/Fonts/msyhbd.ttc"
  mono_font_path: "C:/Windows/Fonts/consola.ttf"


verify_config:
  max_verify_rounds: 2

wkhtmltopdf_path:
  path: /usr/local/bin/wkhtmltopdf

planner:
  use_demonstration: True