# config.yaml
models:
  default: mimo_openrouter   # 默认使用的模型 id

  gpt-4o-mini:
    provider: openrouter
    model_name: openai/gpt-4o-mini
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  deepseek-v3.1-nex-n1:
    provider: openrouter
    model_name: nex-agi/deepseek-v3.1-nex-n1:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false
  
  mimo_openrouter:
    provider: openrouter
    model_name: xiaomi/mimo-v2-flash:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false

# font:
#   chinese: /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
font:
  chinese: C:/Windows/Fonts/msyh.ttc

verify_config:
  max_verify_rounds: 2

wkhtmltopdf_path:
  path: E:/wkhtmltopdf/bin/wkhtmltopdf.exe

planner:
  use_demonstration: True