# config.yaml
models:
  default: qwenplus_dashscope   # 默认使用的模型 id

  deepseek:
    provider: openrouter
    model_name: deepseek/deepseek-chat-v3.1:free
    base_url_env: https://openrouter.ai/api/v1
    stream: true

  qwen3max_dashscope:
    provider: dashscope
    model_name: qwen3-max
    stream: true

  qwenplus_dashscope:
    provider: dashscope
    model_name: qwen-plus
    stream: true
