# config.yaml
models:
  default: grok   # 默认使用的模型 id

  grok:
    provider: openrouter
    model_name: x-ai/grok-4.1-fast:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false

  kimi:
    provider: openrouter
    model_name: moonshotai/kimi-k2:free
    base_url_env: https://openrouter.ai/api/v1
    stream: false
  
  qwen3max_dashscope:
    provider: dashscope
    model_name: qwen3-max
    stream: false

  qwenplus_dashscope:
    provider: dashscope
    model_name: qwen-plus
    stream: false

  qwenflash_dashscope:
    provider: dashscope
    model_name: qwen-flash
    stream: false

font:
  chinese: /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc

verify_config:
  max_verify_rounds: 2
